version: '3.8'

services:
  web-master:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8000"
    environment:
      - NODE_ROLE=master
      - NODE_NAME=master.asn.local
      - MASTER_URL=main.curl.im
      - DATABASE_URL=mysql+pymysql://user:password@db/asn_scanner
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=asn_scanner
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  redis:
    image: redis:6.2-alpine
    restart: always

volumes:
  mysql_data: 